### ISSUE TITLE
Huge repository

### ISSUE THREAD

**Issue by mdorier** [ROSS-org/ROSS#108]
Cloning the ROSS repository leads to the download of about 650 MB of data, for what seems to be a small code. Maybe some unwanted binaries got committed to the repo at some point and not properly removed. In any case it would probably be better to start providing an archive with release versions rather than asking users to "git clone" the entire repository?

**Comment by nmcglohon** [comment]
The culprit is the objects database. Perhaps repacking or pruning might help.

**Comment by gonsie** [comment]
The easiest solution is to adjust the clone command (which we could add to the Readme):
`git clone --depth=1 git@github.com:carothersc/ROSS.git`

To actually attempt to the issue, we could do some git magic so that master branch doesn’t have the full history, ensuring that a clone of master is quick. The source of the problem is caused by a bunch of rnf XML and .rt files (routing tables?) are taking up the most space. The largest is over 1 MB, even when compressed. 

Thus, there seem to be a few options:
- Remove the XML and .rt files from the repo (deleting them forever)
- Do some git magic to move these files to a different branch, ensuring a clone of master is quick
- Change the main branch from "master" to something else (e.g., "stable") [which is slightly less git magic].
- Move some of the historic commits (maybe pre-SR or pre-github?) to a different repo

**Comment by gonsie** [comment]
Some details on how the different clone arguments stack up:

arg | repo objects |  size | time |
------|-|-|-|
| `--depth=1` | 110 | 149.90 KiB | 23 s |
| `-b master --single-branch` | 8731 | 64.69 MiB | 26 s |
| none | 44029 | 634.28 MiB | 75 s |

**Comment by gonsie** [comment]
Deleting the `gh-pages` branch has shrunk the repository considerably. A basic clone now is ~73 MiB. The website is now at [ROSS-org/ross-org.github.io](https://github.com/ROSS-org/Ross-org.github.io)
